language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
services:
  - docker
script:
  - pytest *.py
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: main