language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
services:
  - docker
script:
  - pytest **/*.py
before_install:
- pip install awscli
- export PATH=$PATH:$HOME/.local/bin
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master